apiVersion: v1
kind: Service
metadata:
  name: metadata
spec:
  selector:
    app: metadata
  ports:
    - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  selector:
    matchLabels:
      app: metadata
  replicas: 1
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
        - name: metadata
          image: "{{ .Values.images.metadata }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          env:
            - name: DATABASE_URL
              value: "{{ .Values.env.pgUrl }}"
          ports:
            - containerPort: 8000

