apiVersion: v1
kind: Service
metadata:
  name: ingestion
spec:
  selector:
    app: ingestion
  ports:
    - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
spec:
  selector:
    matchLabels:
      app: ingestion
  replicas: 1
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: "{{ .Values.images.ingestion }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          env:
            - name: NATS_URL
              value: "{{ .Values.env.natsUrl }}"
            - name: MINIO_ENDPOINT
              value: "{{ .Values.env.minioEndpoint }}"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: user
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: pass
            - name: BUCKET
              value: audio
          ports:
            - containerPort: 8000

