apiVersion: v1
kind: Service
metadata:
  name: asr
spec:
  selector:
    app: asr
  ports:
    - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr
spec:
  selector:
    matchLabels:
      app: asr
  replicas: 1
  template:
    metadata:
      labels:
        app: asr
    spec:
      containers:
        - name: asr
          image: "{{ .Values.images.asr }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          env:
            - name: NATS_URL
              value: "{{ .Values.env.natsUrl }}"
          ports:
            - containerPort: 8000

