{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai2text.fullname" . }}-gateway
  labels:
    {{- include "ai2text.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "ai2text.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        {{- include "ai2text.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
    spec:
      containers:
      - name: gateway
        image: "{{ .Values.global.registry }}/{{ .Values.gateway.image.repository }}:{{ .Values.global.imageTag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.gateway.resources | nindent 10 }}
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: NATS_URL
          value: "nats://{{ .Release.Name }}-nats:4222"
{{- end }}

