openapi: 3.0.3
info:
  title: api-gateway
  version: 0.1.0
paths:
  /v1/audio:
    post:
      summary: Ingest audio file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: ok
  /v1/transcripts/{audio_id}:
    get:
      summary: Get transcript
      parameters:
        - name: audio_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
  /v1/search:
    get:
      summary: Search transcripts
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok

