name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*.*.*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/gateway

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: pip install uv
      
      - name: Install dependencies
        run: uv pip install -e .[dev] --system
      
      - name: Run tests
        run: pytest --cov=app --cov-report=xml
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: pip install uv
      
      - name: Install dependencies
        run: uv pip install -e .[dev] --system
      
      - name: Run ruff
        run: ruff check app/ tests/
      
      - name: Run black
        run: black --check app/ tests/
      
      - name: Run mypy
        run: mypy app/

  contract-tests:
    name: Contract Tests (BLOCKS PR)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: service-repo
      
      - name: Checkout contracts repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/ai2text-contracts
          path: contracts-repo
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install pytest pytest-asyncio httpx jsonschema pyyaml
      
      - name: Validate OpenAPI spec
        run: |
          cd contracts-repo/codegen
          make validate || exit 1
      
      - name: Run Gateway contract tests
        working-directory: service-repo
        env:
          CONTRACTS_PATH: ../contracts-repo
        run: |
          cd ../../tests/contract
          pytest gateway/ -v --tb=short || {
            echo "❌ Contract tests FAILED - PR will be blocked"
            exit 1
          }

  build:
    name: Build & Push Image
    needs: [test, lint, contract-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

