openapi: 3.0.3
info:
  title: search
  version: 0.1.0
paths:
  /v1/search:
    get:
      summary: Semantic search
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok

