# Embeddings configuration

# Output directory
output_dir: "models/embeddings"

# Word2Vec parameters
min_count: 2
vector_size: 256
window: 5
workers: 4
epochs: 10

# Phonetic embeddings (Phon2Vec)
phonetic:
  enabled: true
  vector_size: 128
  tone_token: true     # append tone code to syllables
  use_telex: true      # use Telex-like tone markers
  normalize_diacritics: true

# FAISS index params (for fast similarity search)
faiss:
  enabled: false
  nlist: 1024          # IVF list size
  nprobe: 16           # search probes

